version: '3'

services:
  db:
    image: mysql
    container_name: db_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306

